export const cdata = [
  {
    cid: 'c1',
    name: 'Lal Kitab',
    img: 'lalkitab.png',
    alt: 'random',
    rating: 4.9,
    highlights: ["Lal Kitab Kundali", "Singinficance of planets", "Remedial treatment"],
    tagline: ["Just 1 year of progress", " 2 hours a week to reach your goals"],
    price: "40,000",
    featured: true,
  },
  {
    cid: 'c2',
    name: 'Mobile Numerology',
    img: 'mobile.png',
    alt: 'random',
    rating: 4.0,
    highlights: ["Introduction to Numerology", "Number and planets", "How to grids"],
    tagline: ["One week of transformation", "1 hour daily (flexible time)"],
    price: "4,500",
    featured: true,
  },
  {
    cid: 'c3',
    name: 'KP Astrology',
    img: 'kpchakra.png',
    alt: 'random',
    rating: 5.0,
    highlights: ["Advanced KP Astrology", "Accurate event prediction", "House activation"],
    tagline: ["6 months of excellence", "2 hours a week is all you need"],
    price: "20,000",
    featured: true,
  },
  {
    cid: 'c4',
    name: 'Palmistry',
    img: 'hand.png',
    alt: 'random',
    rating: 4.9,
    highlights: ["Lal Kitab Kundali", "Singinficance of planets", "Remedial treatment"],
    tagline: ["Just 1 year of progress", " 2 hours a week to reach your goals"],
    price: "40,000",
    featured: true,
  }
]
